# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xlsx_read_ <- function(path, sheet_paths, sheet_names, comments_paths) {
    .Call('_tidyxl_xlsx_read_', PACKAGE = 'tidyxl', path, sheet_paths, sheet_names, comments_paths)
}

xlsx_formats_ <- function(path) {
    .Call('_tidyxl_xlsx_formats_', PACKAGE = 'tidyxl', path)
}

xlsx_sheet_files_ <- function(path) {
    .Call('_tidyxl_xlsx_sheet_files_', PACKAGE = 'tidyxl', path)
}

xlsx_validation_ <- function(path, sheet_paths, sheet_names) {
    .Call('_tidyxl_xlsx_validation_', PACKAGE = 'tidyxl', path, sheet_paths, sheet_names)
}

xlsx_names_ <- function(path) {
    .Call('_tidyxl_xlsx_names_', PACKAGE = 'tidyxl', path)
}

xlex_ <- function(x) {
    .Call('_tidyxl_xlex_', PACKAGE = 'tidyxl', x)
}

