# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xlsx_read_ <- function(path, sheets, names, comments_paths) {
    .Call('tidyxl_xlsx_read_', PACKAGE = 'tidyxl', path, sheets, names, comments_paths)
}

xlsx_sheets_ <- function(path) {
    .Call('tidyxl_xlsx_sheets_', PACKAGE = 'tidyxl', path)
}

