# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xlsx_read_ <- function(path, sheets) {
    .Call('tidyxl_xlsx_read_', PACKAGE = 'tidyxl', path, sheets)
}

zip_xml <- function(zip_path, file_path) {
    invisible(.Call('tidyxl_zip_xml', PACKAGE = 'tidyxl', zip_path, file_path))
}

